export const videos = [
  "https://videos.pexels.com/video-files/30280414/12980115_1440_2560_25fps.mp4",
  "https://videos.pexels.com/video-files/5532771/5532771-sd_226_426_25fps.mp4",
  "https://videos.pexels.com/video-files/30043254/12887771_1080_1920_30fps.mp4",
  "https://videos.pexels.com/video-files/28836213/12491352_1440_2560_30fps.mp4",
];

export const messages = [
  {
    id: "1",
    username: "johndoe",
    lastMessage: "Check out my new post!",
    time: "2h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    isVerified: true,
  },
  {
    id: "2",
    username: "instagram",
    lastMessage: "New features available",
    time: "1d",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    isVerified: false,
  },
  {
    id: "3",
    username: "elonmusk",
    lastMessage: "To the moon 🚀",
    time: "3d",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    isVerified: false,
  },
  {
    id: "4",
    username: "techcrunch",
    lastMessage: "Your interview is live!",
    time: "5h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    isVerified: true,
  },
  {
    id: "5",
    username: "maria_dev",
    lastMessage: "Thanks for the feedback.",
    time: "1h",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    isVerified: false,
  },
  {
    id: "6",
    username: "funny_memes",
    lastMessage: "😂😂😂",
    time: "3m",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    isVerified: false,
  },
  {
    id: "7",
    username: "travel_buddy",
    lastMessage: "Just landed in Bali! 🌴",
    time: "7h",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    isVerified: false,
  },
];

export const requests = [
  {
    id: "r1",
    username: "new_user1",
    lastMessage: "Hey, mind connecting?",
    time: "10m",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    isVerified: false,
  },
  {
    id: "r2",
    username: "stranger123",
    lastMessage: "Nice profile!",
    time: "1h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    isVerified: false,
  },
  {
    id: "r3",
    username: "someone_unknown",
    lastMessage: "Hi 👋",
    time: "30m",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    isVerified: false,
  },
];

export const blocked = [
  {
    id: "b1",
    username: "spam_bot",
    lastMessage: "You won a prize!",
    time: "1w",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/99.jpg",
    isVerified: false,
  },
  {
    id: "b2",
    username: "troll_account",
    lastMessage: "You're dumb lol",
    time: "2w",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/98.jpg",
    isVerified: false,
  },
];

export const notes = [
  {
    id: "1",
    username: "johndoe",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    note: "At the beach 🌊",
    isVerified: false,
  },
  {
    id: "2",
    username: "janedoe",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    note: "Working late...",
    isVerified: false,
  },
  {
    id: "3",
    username: "alex",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    note: "Gym session done 💪",
    isVerified: false,
  },
  {
    id: "4",
    username: "emilyrose",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    note: "Weekend vibes 🎉",
    isVerified: false,
  },
  {
    id: "5",
    username: "coderlife",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    note: "Debugging all night 🐛",
    isVerified: false,
  },
  {
    id: "6",
    username: "mysteryman",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    note: "Thinking about life 🤔",
    isVerified: false,
  },
];

export const mockChatMessages = [
  {
    id: "1",
    sender: "john",
    text: "Hey! Are you coming to the party tonight? 🎉",
    timestamp: "9:00 PM",
    isOwnMessage: false,
  },
  {
    id: "2",
    sender: "me",
    text: "Yeah, I'll be there around 10!",
    timestamp: "9:01 PM",
    isOwnMessage: true,
  },
  {
    id: "3",
    sender: "john",
    text: "Awesome. See you there!",
    timestamp: "9:02 PM",
    isOwnMessage: false,
  },
];

export const testComments = [
  {
    id: "1",
    username: "travel_lover",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    text: "This sunset is absolutely stunning! Where was this taken? 🌅",
    time: "2h ago",
    liked: false,
    likes: 24,
    isVerified: true,
    showReplies: false,
    replies: [
      {
        id: "1-1",
        username: "adventure_photographer",
        avatar: "https://randomuser.me/api/portraits/men/22.jpg",
        text: "Thanks! It was in Santorini, Greece. The best sunsets I've ever seen!",
        time: "1h ago",
        liked: true,
        likes: 8,
        isVerified: true,
        showReplies: false,
        replies: [],
      },
      {
        id: "1-2",
        username: "wanderlust_jane",
        avatar: "https://randomuser.me/api/portraits/women/45.jpg",
        text: "I was there last summer! The Oia sunset view is unmatched.",
        time: "45m ago",
        liked: false,
        likes: 3,
        isVerified: false,
        showReplies: false,
        replies: [],
      },
    ],
  },
  {
    id: "2",
    username: "food_critic",
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    text: "That dish looks incredible! What's the restaurant called?",
    time: "3h ago",
    liked: true,
    likes: 12,
    isVerified: false,
    showReplies: false,
    replies: [
      {
        id: "2-1",
        username: "chef_mike",
        avatar: "https://randomuser.me/api/portraits/men/88.jpg",
        text: "It's from my new place - The Rustic Table. Come visit us!",
        time: "2h ago",
        liked: false,
        likes: 5,
        isVerified: true,
        showReplies: false,
        replies: [],
      },
    ],
  },
  {
    id: "3",
    username: "fitness_guru",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    text: "Amazing progress! Keep up the hard work 💪",
    time: "5h ago",
    liked: false,
    likes: 18,
    isVerified: true,
    showReplies: false,
    replies: [],
  },
  {
    id: "4",
    username: "tech_enthusiast",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    text: "Just got this phone too. The camera is next level!",
    time: "1d ago",
    liked: false,
    likes: 7,
    isVerified: false,
    showReplies: false,
    replies: [
      {
        id: "4-1",
        username: "photo_pro",
        avatar: "https://randomuser.me/api/portraits/women/23.jpg",
        text: "Right? The night mode is game-changing for photography.",
        time: "22h ago",
        liked: true,
        likes: 4,
        isVerified: false,
        showReplies: false,
        replies: [],
      },
      {
        id: "4-2",
        username: "gadget_reviewer",
        avatar: "https://randomuser.me/api/portraits/men/34.jpg",
        text: "How's the battery life treating you?",
        time: "20h ago",
        liked: false,
        likes: 2,
        isVerified: true,
        showReplies: false,
        replies: [
          {
            id: "4-2-1",
            username: "tech_enthusiast",
            avatar: "https://randomuser.me/api/portraits/men/12.jpg",
            text: "Surprisingly good! Lasts me a full day with heavy use.",
            time: "19h ago",
            liked: false,
            likes: 1,
            isVerified: false,
            showReplies: false,
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: "5",
    username: "art_lover",
    avatar: "https://randomuser.me/api/portraits/women/56.jpg",
    text: "Your artwork is incredible! Do you sell prints?",
    time: "2d ago",
    liked: true,
    likes: 32,
    isVerified: false,
    showReplies: false,
    replies: [
      {
        id: "5-1",
        username: "creative_soul",
        avatar: "https://randomuser.me/api/portraits/women/77.jpg",
        text: "Thank you! Yes, I have an online store - link in my bio!",
        time: "1d ago",
        liked: false,
        likes: 6,
        isVerified: true,
        showReplies: false,
        replies: [],
      },
      {
        id: "5-2",
        username: "design_collector",
        avatar: "https://randomuser.me/api/portraits/men/89.jpg",
        text: "Just ordered two prints! Can't wait to see them in person.",
        time: "18h ago",
        liked: true,
        likes: 3,
        isVerified: false,
        showReplies: false,
        replies: [],
      },
    ],
  },
];

export const sampleNotifications = [
  {
    id: 1,
    type: "like",
    user: {
      name: "johndoe",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    postImage: "https://picsum.photos/id/10/200/200",
    time: "2h ago",
    read: false,
  },
  {
    id: 2,
    type: "comment",
    user: {
      name: "janedoe",
      avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    text: "Nice photo!",
    postImage: "https://picsum.photos/id/11/200/200",
    time: "5h ago",
    read: false,
  },
  {
    id: 3,
    type: "follow",
    user: {
      name: "traveler",
      avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    time: "1d ago",
    read: true,
  },
  {
    id: 4,
    type: "mention",
    user: {
      name: "photographer",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    text: "Check out this photo!",
    postImage: "https://picsum.photos/id/12/200/200",
    time: "2d ago",
    read: true,
  },
];

export const initialStories = [
  {
    id: 1,
    username: "you",
    image: "https://i.pravatar.cc/150?img=1",
    hasUnseenStory: false,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    username: "john",
    image: "https://i.pravatar.cc/150?img=2",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    username: "lisa",
    image: "https://i.pravatar.cc/150?img=3",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    username: "mike",
    image: "https://i.pravatar.cc/150?img=4",
    hasUnseenStory: false,
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    username: "ella",
    image: "https://i.pravatar.cc/150?img=5",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 6,
    username: "dave",
    image: "https://i.pravatar.cc/150?img=6",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    username: "sara",
    image: "https://i.pravatar.cc/150?img=7",
    hasUnseenStory: false,
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    username: "alex",
    image: "https://i.pravatar.cc/150?img=8",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    username: "nina",
    image: "https://i.pravatar.cc/150?img=9",
    hasUnseenStory: false,
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    username: "leo",
    image: "https://i.pravatar.cc/150?img=10",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 11,
    username: "maya",
    image: "https://i.pravatar.cc/150?img=11",
    hasUnseenStory: true,
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 12,
    username: "ryan",
    image: "https://i.pravatar.cc/150?img=12",
    hasUnseenStory: false,
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  },
];

export const sampleReels = [
  {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    user: {
      username: "travel_enthusiast",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    caption: "Exploring the beautiful beaches of Bali 🌴 #travel #bali",
    music: "Original Sound - Travel Vibes",
  },
  {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    user: {
      username: "fitness_guru",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    caption:
      "Morning workout routine to start your day right! 💪 #fitness #workout",
    music: "Popular Song - Artist Name",
  },
  {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    user: {
      username: "foodie_adventures",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    caption:
      "Homemade pasta from scratch - so worth the effort! 🍝 #foodie #cooking",
    music: "Cooking Time - Chef Beats",
  },
  {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    user: {
      username: "pet_lover",
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    caption: "My golden retriever's first swim! So proud 🐕 #dogs #pets",
    music: "Happy Puppy - Animal Sounds",
  },
  {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    user: {
      username: "tech_reviewer",
      avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    },
    caption:
      "Unboxing the latest smartphone - is it worth the hype? 📱 #tech #gadgets",
    music: "Tech Beats - Electronic Music",
  },
];

export const samplePosts = [
  {
    id: "1",
    username: "john",
    avatar: "https://i.pravatar.cc/150?img=2",
    image: "https://picsum.photos/400/400?random=1",
    caption: "Exploring the mountains! #adventure #nature",
    likes: 342,
    comments: 28,
    timeAgo: "2h ago",
    isLiked: false,
    isBookmarked: false,
    saves: 12,
  },
  {
    id: "2",
    username: "lisa",
    avatar: "https://i.pravatar.cc/150?img=3",
    image: "https://picsum.photos/400/400?random=2",
    caption: "Coffee time ☕️ #morningvibes",
    likes: 128,
    comments: 12,
    timeAgo: "1h ago",
    isLiked: true,
    isBookmarked: true,
    saves: 12,
  },
  {
    id: "3",
    username: "traveler",
    avatar: "https://i.pravatar.cc/150?img=4",
    image: "https://picsum.photos/400/400?random=3",
    caption: "Sunset views never get old 🌅",
    likes: 892,
    comments: 42,
    timeAgo: "4h ago",
    isLiked: false,
    isBookmarked: false,
    saves: 12,
  },
  {
    id: "4",
    username: "dave",
    avatar: "https://i.pravatar.cc/150?img=6",
    image: "https://picsum.photos/400/400?random=4",
    caption: "King Sized 🌅",
    likes: 892,
    comments: 42,
    timeAgo: "3h ago",
    isLiked: false,
    isBookmarked: true,
    saves: 12,
  },
];

export const sampleComments = [
  {
    id: "1",
    username: "user1",
    avatar: "https://i.pravatar.cc/150?img=1",
    text: "This is a great post!",
    time: "2h ago",
    liked: false,
    likes: 5,
    isVerified: false,
    replies: [
      {
        id: "1-1",
        username: "author",
        avatar: "https://i.pravatar.cc/150?img=2",
        text: "Thanks for your support!",
        time: "1h ago",
        liked: true,
        likes: 2,
        isVerified: true,
        replies: [],
      },
    ],
    showReplies: false,
  },

  {
    id: "2",
    username: "user2",
    avatar: "https://i.pravatar.cc/150?img=1",
    text: "This is a great post!",
    time: "2h ago",
    liked: false,
    likes: 5,
    isVerified: false,
    replies: [
      {
        id: "1-1",
        username: "author",
        avatar: "https://i.pravatar.cc/150?img=2",
        text: "Thanks for your support!",
        time: "1h ago",
        liked: true,
        likes: 2,
        isVerified: true,
        replies: [],
      },
    ],
    showReplies: false,
  },
];
