export const messages = [
  {
    id: "1",
    username: "johndoe",
    lastMessage: "Check out my new post!",
    time: "2h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    isVerified: true,
  },
  {
    id: "2",
    username: "instagram",
    lastMessage: "New features available",
    time: "1d",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    isVerified: false,
  },
  {
    id: "3",
    username: "elonmusk",
    lastMessage: "To the moon 🚀",
    time: "3d",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    isVerified: false,
  },
  {
    id: "4",
    username: "techcrunch",
    lastMessage: "Your interview is live!",
    time: "5h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    isVerified: true,
  },
  {
    id: "5",
    username: "maria_dev",
    lastMessage: "Thanks for the feedback.",
    time: "1h",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    isVerified: false,
  },
  {
    id: "6",
    username: "funny_memes",
    lastMessage: "😂😂😂",
    time: "3m",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    isVerified: false,
  },
  {
    id: "7",
    username: "travel_buddy",
    lastMessage: "Just landed in Bali! 🌴",
    time: "7h",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    isVerified: false,
  },
];

export const requests = [
  {
    id: "r1",
    username: "new_user1",
    lastMessage: "Hey, mind connecting?",
    time: "10m",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    isVerified: false,
  },
  {
    id: "r2",
    username: "stranger123",
    lastMessage: "Nice profile!",
    time: "1h",
    unread: true,
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    isVerified: false,
  },
  {
    id: "r3",
    username: "someone_unknown",
    lastMessage: "Hi 👋",
    time: "30m",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    isVerified: false,
  },
];

export const blocked = [
  {
    id: "b1",
    username: "spam_bot",
    lastMessage: "You won a prize!",
    time: "1w",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/men/99.jpg",
    isVerified: false,
  },
  {
    id: "b2",
    username: "troll_account",
    lastMessage: "You're dumb lol",
    time: "2w",
    unread: false,
    avatar: "https://randomuser.me/api/portraits/women/98.jpg",
    isVerified: false,
  },
];

export const notes = [
  {
    id: "1",
    username: "johndoe",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    note: "At the beach 🌊",
    isVerified: false,
  },
  {
    id: "2",
    username: "janedoe",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    note: "Working late...",
    isVerified: false,
  },
  {
    id: "3",
    username: "alex",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    note: "Gym session done 💪",
    isVerified: false,
  },
  {
    id: "4",
    username: "emilyrose",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    note: "Weekend vibes 🎉",
    isVerified: false,
  },
  {
    id: "5",
    username: "coderlife",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    note: "Debugging all night 🐛",
    isVerified: false,
  },
  {
    id: "6",
    username: "mysteryman",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    note: "Thinking about life 🤔",
    isVerified: false,
  },
];
